### PR TITLE
TST: added missing pytest dependencies

### PR DESCRIPTION
**Pull request by mrakitin**
Replaces https://github.com/NSLS-II/suitcase-tiff/pull/12.

The message also appears on Travis: https://travis-ci.org/NSLS-II/suitcase-tiff/builds/492291104#L618.

### CODE REVIEW

**Comment by awalter-bnl** [comment]
continuing the previous conversation here, I am still not sure why they are needed. Perhaps it is a mac thing but we don't use them.

**Comment by mrakitin** [comment]
No, I don't thing it's a Mac thing anymore as it used to appear in the tests on Travis: https://travis-ci.org/NSLS-II/suitcase-tiff/builds/492291104#L618.

**Comment by danielballan** [comment]
Some quick Googling didn't uncover others' talking about this. Have you seen this before, @tacaswell? Is pytest taking the position that we should be using pytest-benchmark?

**Comment by awalter-bnl** [comment]
> No, I don't thing it's a Mac thing anymore as it used to appear in the tests on Travis: https://travis-ci.org/NSLS-II/suitcase-tiff/builds/492291104#L618.

Thanks for the link @mrakitin I am now convinced that it is not just an issue on your end, and we should be looking to fix it. I am still confused as to why it is required

**Comment by mrakitin** [comment]
Thanks @awalter-bnl! I agree it's not clear why we get this missing requirement. The source code of pytest does not have any mention of the `pytest-benchmark`. Maybe it comes from its own dependency somehow, but I don't know for sure.

**Comment by danielballan** [comment]
For what it's worth, I can reproduce this locally as well, in a clean venv on Ubuntu, so it can't be due to some configuration that Travis-CI and @mrakitin's laptop happen to share.

Some further Googling didn't turn up anything. Unless we learn more, my personal inclination is to ignore the message, rather than pick up dependencies that we aren't actually using.

**Comment by tacaswell** [comment]
In https://github.com/NSLS-II/suitcase-utils/blob/136f3190b890f89ffd4f6f988d5d630e24b96dbd/suitcase/utils/tests/conftest.py#L6 we import `ophyd.tests.conftest` which in turn imports `caproto.tests.conftest` which has a conditional import of `pytest.benchmark` and `asv` ( https://github.com/NSLS-II/caproto/blob/ef55a27091402b9cf9961566f5d9536f43352b72/caproto/tests/conftest.py#L632-L639 )

I suspect we should put these in `requirements-dev` file rather than `setup.py`.

**Comment by danielballan** [comment]
This would be my preferred solution: https://github.com/NSLS-II/ophyd/pull/701. This is something I intended to do anyway... we don't want to be debugging a curio install on Travis just to be able to use `hw`.

**Comment by danielballan** [comment]
Since NSLS-II/ophyd#701 was merged with broad approval, I gather we can close this as resolved upstream? I leave it to @mrakitin to confirm.

**Comment by mrakitin** [comment]
Sounds great, thanks for following up, @danielballan.

**Pull request closed without merging**
